[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 2000
multiplier = 8

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
dynamic_padding = false
opacity = 0.85
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 5
